### ISSUE TITLE
what is the root password? I maybe need to install some apps

### ISSUE THREAD

**Issue by v2tony** [hectorm/docker-xubuntu#1]
dpkg: error: requested operation requires superuser privilege
and double click appimage file ,it works nothing

**Comment by hectorm** [comment]
There is no root password and you should not install any additional packages in a running container, as it will be lost when the container is recreated.

The usual procedure is to extend the image to include all the changes you want. I have other projects that can be used as examples, such as [Steam](https://github.com/hectorm/docker-steam) or [Wine](https://github.com/hectorm/docker-wine).
