### ISSUE TITLE
Add option: For privileged user

### ISSUE THREAD

**Issue by polhaghverdian** [hectorm/docker-xubuntu#11]
Hi,

You really made a great container! One wish i have, is the option to add an privileged user.

**Comment by hectorm** [comment]
What do you want to do with a privileged user?

Right now you can make the unprivileged user escalate by setting the environment variable `UNPRIVILEGED_USER_GROUPS` to `sudo`.

**Comment by hectorm** [comment]
I think the `UNPRIVILEGED_USER_GROUPS` option solves the problem, but feel free to reopen the issue if you can't achieve what you need this way.
