### ISSUE TITLE
please consider to use root user

### ISSUE THREAD

**Issue by timiil** [hectorm/docker-xubuntu#17]
i am trying to use this great project to do some CI CD work，so i may have a lot of root user operations something like swapon or etc... 
so if a pure qemu-Ubuntu without GUI，with the root user usage，that will too good to be TRUE! :)

**Comment by hectorm** [comment]
If you set the variable `UNPRIVILEGED_USER_GROUPS` to `sudo` and `UNPRIVILEGED_USER_PASSWORD` to an empty string you will be able to use sudo without a password.
