### ISSUE TITLE
Share drive .thinclient_drives

### ISSUE THREAD

**Issue by nicknesh** [hectorm/docker-xubuntu#18]
I use RDP client xfreerdp with '/drive:share,/some-path/share/ '. On previous version based on 20.04 I see ~/.thinclient_drives/share, but on image based on 22.04 .thinclient_drives is empty.

**Comment by hectorm** [comment]
Could you confirm if adding these options solves the issue?
`--cap-add SYS_ADMIN --device /dev/fuse:/dev/fuse`

**Comment by nicknesh** [comment]
Yes, it solve issues.
Thanks!

**Comment by aratar-orome** [comment]
Hi,

I have the same problems with the current version. The recommended options does not help. Any other idea?

**Comment by nicknesh** [comment]
Hi,
Please try 
`--security-opt apparmor:unconfined`

**Comment by aratar-orome** [comment]
Thanks, actually both of your recommended options were required to get it running.
