### ISSUE TITLE
Depending on how I start the container the UI is looking differently

### ISSUE THREAD

**Issue by irixxxx** [hectorm/docker-xubuntu#19]
Start commands and screenshots:

``docker run --detach --shm-size 3g --publish 3325:3322/tcp --publish 3392:3389/tcp --privileged devel``

![Screenshot 2023-02-28 at 09 44 17](https://user-images.githubusercontent.com/31696370/221800568-cbeb1c54-248d-450b-b406-d0235314be55.png)

``docker run --detach --shm-size 3g --publish 3324:3322/tcp --publish 3391:3389/tcp --mount type=bind,source=$PWD/src,target=/home/user/src --mount type=bind,source=$PWD/opt,target=/home/user/opt --privileged  devel``

![Screenshot 2023-02-28 at 09 42 16](https://user-images.githubusercontent.com/31696370/221800726-4c88485c-3404-4e24-92cf-1e4dcc0202b9.png)

Dockerfile for tag devel:

```
FROM hectormolinero/xubuntu

RUN apt-get update
RUN mkdir -p /home/user && chown -R 1000:1000 /home/user
```

docker running on an M1 Macbook.

**Comment by hectorm** [comment]
The problem is that if you mount a directory inside `/home/user/`, that directory is no longer empty, and during container startup the `/etc/skel/` files are not copied when the user is created.

I have released a new version that rethinks how session variables are defined to avoid copying anything from `/etc/skel/`. Could you test if `v105` fixes the problem?

I also noticed that you are using the old image `hectormolinero/xubuntu`, change it to `hectorm/xubuntu`.

**Comment by irixxxx** [comment]
It froze in initialization, since the ``chown -R`` for the home directory recursed into the mounts. Better only change the copied files plus the home directory itself. I did this:

```
diff --git a/scripts/bin/container-init b/scripts/bin/container-init
index a1d0968..7071517 100755
--- a/scripts/bin/container-init
+++ b/scripts/bin/container-init
@@ -47,7 +47,7 @@ fi
 UNPRIVILEGED_USER_HOME=$(getent passwd "${UNPRIVILEGED_USER_NAME:?}" | cut -d: -f6)
 if [ ! -e "${UNPRIVILEGED_USER_HOME:?}"/.profile ]; then
        cp -aT /etc/skel/ "${UNPRIVILEGED_USER_HOME:?}" 2>/dev/null ||:
-       chown -R "${UNPRIVILEGED_USER_NAME:?}:" "${UNPRIVILEGED_USER_HOME:?}" 2>/dev/null ||:
+       (cd "${UNPRIVILEGED_USER_HOME:?}" && chown "${UNPRIVILEGED_USER_NAME:?}:" $(cd /etc/skel && find .)) 2>/dev/null ||:
 fi
 
 # Create /run/dbus/ directory if it does not exist
```

With this change, it works as expected.

**Comment by hectorm** [comment]
The problem with the proposed change is that it does not work with paths containing spaces, but I implemented a similar solution in `v106`, could you confirm if this solves the problem?

**Comment by irixxxx** [comment]
Yes, that works as well. I had chosen the simpler approach since I reckoned files in /etc/skel would never had spaces in them, but better safe than sorry.
