### ISSUE TITLE
hectorm/xubuntu:v112-amd64 does not work by default

### ISSUE THREAD

**Issue by adrianog** [hectorm/docker-xubuntu#24]
Run and can rdp connect and login with "user" "password" - then blue screen with nothing happening.

Added:
-v /sys/fs/cgroup:/sys/fs/cgroup:rw --cgroupns=host \
same problem

Added:
  --privileged \
and it works.

How are you getting around: https://github.com/moby/moby/issues/42275
for systemd? you need   --privileged \, right?

Is that the problem?

**Comment by hectorm** [comment]
This image does not use systemd, nor does it need to be run with the `--privileged` option. See the `run.sh` file to get an idea of the proper way to run it.

Can you give me more details about your environment and the full command you are running the image with to help me understand what might be happening in your case?
