### ISSUE TITLE
Running under MacOS and M2 processor fails

### ISSUE THREAD

**Issue by rusio** [hectorm/docker-xubuntu#30]
Is the image runnable on a MacOS host? When I try running the image on a **MacBook Pro with M2** processor using this command:

```
docker run \
  --name xubuntu \
  --detach \
  --shm-size 2g \
  --publish 3322:3322/tcp \
  --publish 3389:3389/tcp \
  --device /dev/dri:/dev/dri \
  docker.io/hectorm/xubuntu:latest
```

I get the following error:
`docker: Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory.`

I tried removing the --device option, but then I get even more errors:

```
docker run --publish 3322:3322/tcp --publish 3389:3389/tcp docker.io/hectorm/xubuntu
sha1 Fingerprint=0E:D0:94:D4:D3:86:D0:04:0C:C8:D5:68:93:5E:B3:48:9D:6A:CF:42
sha256 Fingerprint=8D:64:9D:5D:27:61:EA:6C:C1:E9:6D:5F:8B:76:C5:1E:CB:F0:EB:F9:D6:FE:A1:86:09:49:89:1C:F9:BE:73:BC
[2024-07-14T12:09:35.373+0000] [INFO ] starting xrdp-sesman with pid 63
[2024-07-14T12:09:35.373+0000] [INFO ] Sesman now listening on /opt/xrdp/var/run/xrdp/sesman.socket
[2024-07-14T12:09:35.376+0000] [INFO ] starting xrdp with pid 62
[2024-07-14T12:09:35.376+0000] [INFO ] address [0.0.0.0] port [3389] mode 1
[2024-07-14T12:09:35.376+0000] [INFO ] listening to port 3389 on 0.0.0.0
[2024-07-14T12:09:35.377+0000] [INFO ] xrdp_listen_pp done
Using default interface naming scheme 'v255'.
dbus-daemon[64]: Failed to start message bus: Failed to bind socket "/run/dbus/system_bus_socket": Permission denied
breakpoint: Failed to write 'change' to '/sys/devices/breakpoint/uevent': Read-only file system
```

Any idea if it is a general error related to MacOS or my setup is lacking something?

**Comment by hectorm** [comment]
I have only tested this image on various Linux distributions, but it should work on macOS without hardware acceleration, so you should remove the `--device` option from the command.

I will try to reproduce the dbus error in a macOS VM at some point, but it is not a priority for me at the moment.

**Comment by hectorm** [comment]
The dbus error did not only happen on macOS and should be fixed in `v119`, can you try again?

**Comment by rusio** [comment]
I can confirm, the dbus error does not occur in v119. Removing the --device option from the command allows running the image under macOS. Thank you for the response and for maintaining this image.
