### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by snaca** [hectorm/docker-xubuntu#4]
I add guest user to sudo group and apt install language-selector-gnome, then selected my language, and logout.
but when I lonin again, nothing happened, still English language.
How can I do next step?

btw, It's a great project for us.
Thank you.

**Comment by hectorm** [comment]
You should not install packages in the container as they will be lost when destroyed.

In this case the correct approach would be to extend the image, install the desired language pack and regenerate the locales.

```Dockerfile
FROM docker.io/hectormolinero/xubuntu:latest

RUN export DEBIAN_FRONTEND=noninteractive \
	&& apt-get update \
	&& apt-get install -y language-pack-es \
	&& rm -rf /var/lib/apt/lists/*

ENV LANG=es_ES.UTF-8 LC_ALL=es_ES.UTF-8
RUN printf '%s\n' "${LANG:?} UTF-8" > /etc/locale.gen \
	&& localedef -c -i "${LANG%%.*}" -f UTF-8 "${LANG:?}" ||:
```
