### ISSUE TITLE
Installed Skype and Google Chrome but not able to run it

### ISSUE THREAD

**Issue by shiroamada** [hectorm/docker-xubuntu#5]
Hi,

I manage to install via https://linuxize.com/post/how-to-install-google-chrome-web-browser-on-ubuntu-18-04/ this tutorial.
The Program Icon appear at the start menu, but when I click and run it, Google Chrome not appear. 
It's go to try.

Are you able to run it? Or any setting need to be done?

Thanks!

**Comment by hectorm** [comment]
In the following issue you will find the reason why it doesn't work: jessfraz/dockerfiles#65

The easiest solution to make it work (considering that adding privileges to a container represents a security risk) would be to run the container with the `--cap-add=SYS_ADMIN` argument.

To perform the installation I used the following Dockerfile:
```Dockerfile
FROM docker.io/hectormolinero/xubuntu:latest

# Install Google Chrome
ARG GOOGLE_CHROME_DEB_URL=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN curl -Lo /tmp/google-chrome.deb "${GOOGLE_CHROME_DEB_URL:?}" \
	&& dpkg -i /tmp/google-chrome.deb || (apt-get update && apt-get install -fy) \
	&& rm -rf /tmp/google-chrome.deb /var/lib/apt/lists/*

# Install Skype
ARG SKYPE_DEB_URL=https://go.skype.com/skypeforlinux-64.deb
RUN curl -Lo /tmp/skype.deb "${SKYPE_DEB_URL:?}" \
	&& dpkg -i /tmp/skype.deb || (apt-get update && apt-get install -fy) \
	&& rm -rf /tmp/skype.deb /var/lib/apt/lists/*
```

Then started the container with the following command:
```sh
docker run \
    --detach \
    --shm-size 2g \
    --cap-add=SYS_ADMIN \
    --publish 3389:3389/tcp \
    --device /dev/dri:/dev/dri \
    YOUR_IMAGE
```

And then connected with FreeRDP with the following command:
```sh
xfreerdp \
    /v:127.0.0.1:3389 \
    /u:guest /p:password \
    /log-level:INFO /cert:ignore \
    /gfx:RFX +gfx-progressive /w:1600 /h:900 \
    /audio-mode:0 /sound:sys:pulse,rate:44100 \
    /microphone:sys:pulse,rate:44100 \
    +clipboard +home-drive \
    -compression -encryption
```

![](https://user-images.githubusercontent.com/852266/103151281-daf5f100-477c-11eb-91b6-c8c46fcb5670.png)

**Comment by 4563453** [comment]
this fix is working nice, thank you. 

for docker-compose:

```
services:
  xubuntu:
    image: registry.ipv6.docker.com/hectorm/xubuntu:latest
    container_name: xubuntu
    cap_add:
      - ALL
      
```
source: https://docs.docker.com/compose/compose-file/compose-file-v3/#cap_add-cap_drop
